- name: Set check mk hostname
  ansible.builtin.set_fact:
    cmk_agent_hostname: "{{ ansible_hostname }}"

- name: Update check mk hostname
  when: cmk_agent_hostprefix is defined
  ansible.builtin.set_fact:
    cmk_agent_hostname: "{{ cmk_agent_hostprefix }}{{ ansible_hostname }}"

- name: Check connection to {{ cmk_agent_cmkserver }}
  when: ansible_facts.os_family == "Windows"
  ansible.windows.win_ping:

- name: Connection check for linux
  when: ansible_facts.system == "Linux"
  ansible.builtin.ping:

- name: Check  current version of {{ cmk_agent_cmkserver }}
  ansible.builtin.uri:
    url: "https://{{ cmk_agent_cmkserver }}/{{ cmk_agent_site }}/check_mk/api/1.0/version"
    headers:
      Authorization: "Bearer {{ cmk_agent_automation_user }} {{ cmk_agent_automation_pwd }}"
      Accept: "application/json"
      Content-Type: "application/json"
  register: cmk_agent_rest_cmkversion

- name: Set fact for cmk_agent_version
  ansible.builtin.set_fact:
    cmk_agent_version: "{{ cmk_agent_rest_cmkversion.x_checkmk_version }}"

- name: Running checkmk version of {{ cmk_agent_cmkserver }}
  ansible.builtin.debug:
    msg: "{{ cmk_agent_version }}"

- name: Running on distributions based on {{ ansible_os_family }}
  ansible.builtin.include_tasks: "_{{ ansible_os_family | lower }}-tasks.yml"
  tags: install-check-mk-agent
