- name: Set check mk hostname
  ansible.builtin.set_fact:
    cmk_agent_hostname: "{{ ansible_hostname }}"

- name: Update check mk hostname
  when: cmk_agent_hostprefix is defined
  ansible.builtin.set_fact:
    cmk_agent_hostname: "{{ cmk_agent_hostprefix }}{{ ansible_hostname }}"

- name: Check connection to {{ cmk_agent_cmkserver }}
  when: ansible_facts.os_family == "Windows"
  ansible.windows.win_ping:

- name: Connection check for linux
  when: ansible_facts.system == "Linux"
  ansible.builtin.ping:

- name: Running on distributions based on {{ ansible_os_family }}
  ansible.builtin.include_tasks: "_{{ ansible_os_family | lower }}-tasks.yml"
  tags: install-check-mk-agent
